### ISSUE TITLE
[bug]: Health check fails on first startup

### ISSUE THREAD

**Issue by arielle88** [Start9Labs/ghost-startos#6]
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

13.0.1 (22A400)

### Browser

Firefox

### Browser Version

109.0.1

### Current Behavior

See steps to reproduce below.

### Expected Behavior

Either the system should warn me it will do this, or the health check should succeed.

### Steps to Reproduce

Steps to reproduce:
1. Install fresh
2. hit start
3. health check fails

Logs indicate that the database is still being created, but there are no warnings that this will happen.

**Comment by k0gen** [comment]
fixed
